categories:
  - Data Source
  - Fastq Manipulation
description: R Markdown based fastq-dump wrapper
long_description: Download and extract reads in fastq/fasta format from NCBI SRA and output a list or list:paired dataset collection.
name: rmarkdown_fastq_dump
owner: mingchen0919
remote_repository_url: https://github.com/statonlab/docker-GRReport/tree/master/aurora-tools/rmarkdown_fastq_dump
type: unrestricted