---
name: aurora_demo_site
owner: mingchen0919
description: A tool for demonstrating the idea of Aurora Galaxy tool development.
long_description: ""
remote_repository_url: ""
type: unrestricted
categories:
  ZZZ test3: ZZZ test3
...
