---
name: aurora_fasta_importer
owner: mingchen0919
description: Import fasta to galaxy by copying uploaded fasta or downloading fasta from an URL.
long_description: ""
remote_repository_url: ""
type: unrestricted
categories:
  - ZZZ test3
...